# Generated by Django 3.0.8 on 2020-07-09 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200709_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifyapidata',
            name='last_used',
        ),
    ]
