# Generated by Django 3.0.8 on 2020-08-11 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_generatedplaylist_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='spotify_auth_required',
        ),
    ]
