# Generated by Django 3.0.8 on 2020-08-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_profile_spotify_auth_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistoptions',
            name='history_duration',
            field=models.CharField(choices=[('long_term', '1 month'), ('short_term', '6 months'), ('medium_term', 'All time')], default='short', max_length=25),
        ),
    ]
