# Generated by Django 3.0.8 on 2020-08-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_playlistoptions_history_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistoptions',
            name='history_duration',
            field=models.CharField(choices=[('long_term', '1 month'), ('short_term', '6 months'), ('medium_term', 'All time')], default='short_term', max_length=25),
        ),
    ]
