# Generated by Django 3.0.8 on 2020-08-13 22:32

from django.db import migrations, models
from datetime import date, datetime


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_auto_20200813_0319"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spotifyapidata", name="authentication_date",
        ),
        migrations.AddField(
            model_name="spotifyapidata",
            name="access_expires_at",
            field=models.DateTimeField(default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="spotifyapidata",
            name="access_token",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="spotifyapidata",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
