# Generated by Django 3.0.8 on 2020-08-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200813_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyapidata',
            name='access_expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
