DEBUG = True

CORS_ORIGIN_WHITELIST = ['http://localhost:3000']
CORS_ORIGIN_ALLOW_ALL = True

ALLOWED_HOSTS = []

SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_REFERRER_POLICY = None
SECURE_HSTS_SECONDS=None
SECURE_HSTS_INCLUDE_SUBDOMAINS=False